import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const style = StyleSheet.create({
  container: {
    flex: 2,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: width * 0.05,
  },
  headerDynamic: {
    width: width * 0.45,
    height: height * 0.2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 75,
  },
  logo: {
    width: width * 0.45, // Ajuste proporcional ao tamanho da tela
    height: height * 0.06,
    resizeMode: "contain",
  },
  slogan: {
    fontSize: width * 0.032,
    color: "#A0A0A0",
    marginBottom: height * 0.1,
    fontWeight: "500",
  },
  card: {
    marginTop: height * 0.001,
    backgroundColor: "#FFFFFF",
    width: width * 0.9,
    borderRadius: 25,
    padding: width * 0.06,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  title: {
    fontSize: width * 0.09,
    fontWeight: "bold",
    color: "#000",
    marginBottom: height * 0.03,
    marginTop: height * 0.03,
    shadowColor: "#FFFFFF",
    shadowOpacity: 0.5,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f2f2f2",
    borderRadius: 15,
    paddingHorizontal: width * 0.04,
    width: "90%",
    height: height * 0.07,
    marginBottom: height * 0.02,
  },
  input: {
    flex: 1,
    fontSize: width * 0.04,
    color: "#333",
    paddingLeft: width * 0.03,
  },
  button: {
    backgroundColor: "#D705F2",
    width: "90%",
    height: height * 0.07,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginTop: height * 0.02,
    shadowColor: "#D705F2",
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  buttonText: {
    color: "#FFF",
    fontSize: width * 0.06,
    fontWeight: "bold",
  },
  orText: {
    color: "#A0A0A0",
    marginVertical: height * 0.025,
    fontSize: width * 0.04,
  },
  socialIcons: {
    flexDirection: "row",
    width: "70%",
    justifyContent: "space-between",
    marginBottom: height * 0.02,
  },
  socialIconCircle: {
    width: width * 0.12,
    height: width * 0.12,
    backgroundColor: "#e3e3e3",
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  boxBottom: {
    marginTop: height * 0.015,
    fontWeight: "500",
    width: width * 0.4,
    height: height * 0.04,
    backgroundColor: "#F2F2F2",
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  forgotPassword: {
    color: "#949494",
    fontSize: width * 0.04,
    fontWeight: "medium",
  },
  registerText: {
    fontSize: width * 0.04,
    color: "#A0A0A0",
    marginTop: height * 0.06,
    marginBottom: height * 0.06,
  },
  registerLink: {
    color: "#AB05F2",
    fontWeight: "bold",
    fontSize: width * 0.04,
  },
});
