import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

// Obtendo largura e altura da tela para responsividade
const { width, height } = Dimensions.get("window");

export const styleHome = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    paddingHorizontal: width * 0.001, // 1% da largura da tela
  },
  headerDynamic: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: height * 0.06, // 6% da altura da tela
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.015,
    borderRadius: 10,
  },
  cardMain: {
    width: "100%",
    flex: 1,
    padding: width * 0.01,
  },
  cabecalho: {
    width: "100%",
    left: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: height * -0.02,
    paddingHorizontal: width * 0.01,
  },
  iconeTop: {
    width: width * 0.1,
    height: height * 0.03,
    resizeMode: "contain",
    right: 45,
  },
  iconeTopCriar: {
    width: width * 0.1,
    height: height * 0.03,
    resizeMode: "contain",
  },
  buttonTop: {
    backgroundColor: "#D705F2",
    borderRadius: width * 0.1,
    width: width * 0.1,
    height: width * 0.1,
    alignItems: "center",
    justifyContent: "center",
    padding: width * 0.015,
  },
  buttonSubtitulo: {
    color: "#fff",
    right: 15,
    flexDirection: "row",
    height: height * 0.03,
    fontSize: width * 0.01,
  },
  IconsTopSubt: {
    width: "20%",
    fontSize: width * 0.04,
    fontWeight: "bold",
  },
  sectionBTNTitle: {
    fontSize: width * 0.03,
    fontWeight: "bold",
    color: "#000",
  },
  sectionTitleICON: {
    right: 18,
    fontSize: width * 0.06,
    fontWeight: "bold",
    color: "#000",
  },
  logoPaginaTitulo: {
    height: height * 0.025,
    right: 30,
    resizeMode: "contain",
  },
  tresPontos: {
    height: height * 0.015,
    resizeMode: "contain",
  },
  iconeSubtitulo: {
    height: height * 0.02,
    left: 5,
    resizeMode: "contain",
  },
  logo: {
    width: width * 0.58,
    height: height * 0.03,
    resizeMode: "contain",
    color: "#fff",
    alignSelf: "center",
    left: 30,
  },
  IconsTop: {
    marginTop: height * 0.01,
    marginLeft: 5,
    flexDirection: "row",
    justifyContent: "center",
    left: 15,
  },
  cardStories: {
    width: "100%",
    backgroundColor: "#FFF",
    borderRadius: 25,
    paddingLeft: width * 0.02,
  },
  cardCabecalho: {
    width: "100%",
    marginTop: 15,
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    padding: 25,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  cardFeed: {
    width: "100%",
    flexDirection: "row", // Alinha os cards em uma linha
    flexWrap: "wrap", // Permite que os cards que excedem o espaço se movam para a próxima linha
    justifyContent: "space-between",
  },
  sessaoStories: {
    right: 6,
    paddingLeft: 10,
  },
  sessaoSUGESTAO: {
    paddingTop: 5,
    paddingBottom: 10,
    borderRadius: 10,
    backgroundColor: "transparent",
  },
  story: {
    width: width * 0.18,
    height: width * 0.18,
    borderRadius: width * 0.09,
    borderWidth: 4,
    borderColor: "#A020F0",
    marginRight: 10,
    backgroundColor: "transparent",
    overflow: "hidden",
    position: "relative",
  },
  clickableStory: {
    backgroundColor: "transparent",
  },

  selectedStory: {
    borderRadius: width * 0.09,
    shadowColor: "#D705F2",
    shadowOpacity: 0.4,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  gradientBorder: {
    position: "absolute",
    width: "100%",
    height: "100%",
    borderRadius: 50,
  },
  title: {
    fontSize: width * 0.09,
    fontWeight: "bold",
    color: "#000",
    marginBottom: height * 0.03,
    marginTop: height * 0.03,
  },
  titleICON: {
    color: "#fff",
    width: 100,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  sectionTitle: {
    fontSize: width * 0.06,
    fontWeight: "bold",
    color: "#000",
    marginBottom: height * 0.03,
    marginTop: height * 0.03,
  },

  cardPost: {
    width: width * 0.48,
    borderRadius: 25,
    padding: width * 0.01,
    paddingBottom: height * 0.02,
    justifyContent: "center",
    position: "relative",
  },
  cardPostSUGESTAO: {
    width: width * 0.48,
    height: 235,
    backgroundColor: "#F2F2F2",
    borderRadius: 20,
    padding: width * 0.01,
    justifyContent: "center",
    position: "relative",
  },
  headerPost: {
    flexDirection: "row",
    paddingBottom: 5,
  },
  infoPostSUGESTAO: {
    flexDirection: "row",
    paddingTop: 10,
    paddingLeft: 8,
  },
  headerPostSUGESTAO: {
    borderRadius: 25,
    width: width * 0.48,
    right: 5,
  },
  perfilSUGESTAO: {
    width: "20%",
    paddingLeft: 5,
    paddingRight: 5,
    paddingBottom: 5,
    paddingTop: 10,
    backgroundColor: "#E3E3E3",
    alignItems: "center",
    borderRadius: 20,
    marginTop: 10,
    marginLeft: 8,
    marginRight: 5,
  },
  profileImage: {
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.05,
    borderWidth: 2.5,
    borderColor: "#A020F0",
    marginRight: width * 0.02,
  },
  profileImageSUGESTAO: {
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.05,
    borderWidth: 2,
    borderColor: "#A020F0",
    marginRight: width * 0.02,
  },
  name: {
    color: "#000",
    fontWeight: "bold",
    fontSize: width * 0.035,
  },
  nameSUGESTAO: {
    color: "#000",
    fontWeight: "bold",
    fontSize: 16,
    backgroundColor: "transparent",
    width: "90%",
    alignItems: "center",
    overflow: "visible",
  },
  saibaMaisSUGESTAO: {
    height: 25,
    left: 35,
    marginTop: 3,
    resizeMode: "contain",
  },
  quemSeguir: {
    color: "#000",
    fontWeight: "bold",
    fontSize: 20,
    backgroundColor: "transparent",
  },
  sugestãoYOU: {
    color: "#9D9D9D",
    fontWeight: "bold",
    fontSize: 12,
    backgroundColor: "transparent",
  },
  iconStyle: {
    width: 40,
    height: 18,
    right: 10,
    resizeMode: "contain",
    alignItems: "center",
    justifyContent: "center",
  },
  infoPost: {
    color: "#000",
    paddingTop: 8,
    paddingBottom: 10,
    justifyContent: "space-between",
    width: "75%",
  },
  infoUserSUGESTAO: {
    paddingTop: 8,
    paddingBottom: 5,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  infoPostUserTime: {
    color: "gray",
    fontWeight: "bold",
    marginTop: 2,
    flexDirection: "row",
  },
  username: {
    color: "gray",
    fontWeight: "bold",
    fontSize: width * 0.02,
  },
  usernameSUGESTAO: {
    color: "#9D9D9D",
    fontWeight: "bold",
    fontSize: 14,
    backgroundColor: "transparent",
    width: "100%",
    height: 15,
    marginTop: 5,
    alignItems: "center",
  },
  buttonSUGESTAO: {
    backgroundColor: "#D705F2",
    width: width * 0.2,
    height: height * 0.04,
    borderRadius: width * 0.025,
    alignItems: "center",
    justifyContent: "center",
    marginTop: height * 0.005,
    marginBottom: height * 0.005,
    shadowColor: "#D705F2",
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  buttonTextSUGESTAO: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  time: {
    color: "gray",
    fontSize: width * 0.02,
  },
  postImage: {
    width: "100%",
    height: undefined,
    aspectRatio: 1,
    borderRadius: width * 0.04,
    backgroundColor: "#FFFFFF",
  },
  footerPost: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: height * 0.001,
  },
  footerLikeComent: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 5,
    right: 5,
  },
  btnLike: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 2,
    width: "30%",
    height: 25,
    resizeMode: "contain",
  },
  likes: {
    marginRight: width * 0.02,
    marginTop: 2.5,
    color: "#959595",
    fontWeight: "bold",
    right: 18,
  },
  btnComentario: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 2,
    width: "30%",
    height: height * 0.03,
    resizeMode: "contain",
  },
  comments: {
    marginRight: width * 0.02,
    marginTop: 2.5,
    color: "#959595",
    fontWeight: "bold",
    right: 18,
  },
  btnCompartilhar: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 2,
    width: "30%",
    height: height * 0.03,
    resizeMode: "contain",
    left: 30,
  },
});
